name: Discord notification
on:
  push:
    branches:
      - testing
      - main
  pull_request:
    branches:
      - testing
      - main
jobs:https://github.com/Baab-platform/baab-admin-frontend/tree/testing
  Notify:
    name: Vendors Dashboard Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_NOTIFICATION }}
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ EVENT_PAYLOAD.head_commit.author.name }} just pushed to {{ EVENT_PAYLOAD.ref }} commit message : {{ EVENT_PAYLOAD.head_commit.message }}'
